# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd473550a34d8331eca7835a5e482acee6281bbf7339d9699d3bb1675e32224d2f6ff7de9520b1a4c187edb6a7b508a67596188fffd3bf9e33541ab9918ab448

test:
  secret_key_base: 85cf4b74992e90a8ad13799e459c2ba05ad0334aa92a083f9062c28a835ca21392a22d1d0022fdda36ea9a86e09cc34fc14fb933cfdd5a925da71104809c56ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
